version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: 2tdata-backend
    networks:
      - 2tdata-network
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: 2tdata-frontend
    networks:
      - 2tdata-network
    ports:
      - "80:80"
    environment:
      # Removed hardcoded VITE_API_BASE_URL to use dynamic detection
      # The frontend will automatically detect the current domain
      VITE_MONGO_EXPRESS_URL: "http://localhost:8081"

networks:
  2tdata-network:
    external: true

