version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: 2tdata-backend
    networks:
      - 2tdata-network
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_URI=mongodb://admin:password@2tdata-mongodb:27017/2TDATA?authSource=admin
      - MONGODB_URI=mongodb://admin:password@2tdata-mongodb:27017/2TDATA?authSource=admin
      - SECRET_KEY=encore
      - JWT_SECRET=encore
      - JWT_EXPIRES_IN=24h
      - SEND_OTP_EMAIL=vietcuong2532k3@gmail.com
      - SEND_OTP_EMAIL_PASSWORD=qcps wsji smea gqxf
      - LOG_LEVEL=info
      - BCRYPT_SALT_ROUNDS=12

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: 2tdata-frontend
    networks:
      - 2tdata-network
    ports:
      - "80:80"
    environment:
      # Removed hardcoded VITE_API_BASE_URL to use dynamic detection
      # The frontend will automatically detect the current domain
      VITE_MONGO_EXPRESS_URL: "http://localhost:8081"

  mongodb:
    image: mongo:latest
    container_name: 2tdata-mongodb
    networks:
      - 2tdata-network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: 2TDATA
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-express:
    image: mongo-express:latest
    container_name: 2tdata-mongo-express
    networks:
      - 2tdata-network
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: 2tdata-mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb

networks:
  2tdata-network:
    external: true

volumes:
  mongodb_data:

