version: '3.8'

services:
  mongodb-dev:
    image: mongo:7.0
    container_name: mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: 2TDATA
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - dev-network

  # Optional: MongoDB Express for GUI management
  mongo-express-dev:
    image: mongo-express:1.0.0
    container_name: mongo-express-dev
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb-dev:27017/
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_BASICAUTH_USERNAME: ""
      ME_CONFIG_BASICAUTH_PASSWORD: ""
    depends_on:
      - mongodb-dev
    networks:
      - dev-network

volumes:
  mongodb_dev_data:

networks:
  dev-network:
    driver: bridge
